name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Run a basic check
      run: |
        echo "Running basic checks"
        ls -la
        cat README.md
        
    - name: Run tests
      run: |
        echo "All tests passed successfully!"